services:
  - type: web
    name: atomic-node-pr03
    env: node
    plan: free
    region: singapore          # Forces the server to be close to India
    
    # This points to your specific project folder
    rootDirectory: Project/PR-03-Converting-HTML-To-Node-In-The-Atomic-Node-Engine

    # Since you have a yarn.lock, we use yarn to install dependencies
    buildCommand: yarn install
    startCommand: node index.js

    # Locks the Node version to match your local environment
    envVars:
      - key: NODE_VERSION
        value: 22.12.0  